print('hello')
print('world')
print('third print0')
print('fourth print')
print('fixed toml adding token')
print('added token to env using $Env:GH_TOKEN = "token"')
print('updated version-bump')
print('added very verbose mode and fixed chatgpt mess')
print('testing a new yml for version bump')
print('added root options to execute the vv mode')
print('modified repo dir in yml')
print('new print')
