import sys

print('hello')
print('world')
print('third print0')
print('fourth print')
print('fixed toml adding token')
print('added token to env using $Env:GH_TOKEN="token"')
print('updated version-bump')
print('added very verbose mode and fixed chatgpt mess')
print('testing a new yml for version bump')
print('added root options to execute the vv mode')
print('modified repo dir in yml')
print('new print')
print('test with no semantic release')

print(sys.executable)
print('end')
print('true end(?)')
print('very true end(?)')
print('ok this is the final one')
print('i was joking, this is the final one')
print('20!')
print('new test by adding fetch tags')
print('help!!!')
print('testing pull with git actions')