print('hello')
print('world')
print('third print0')
print('fourth print')
print('fixed toml adding token')
print('added token to env using $Env:GH_TOKEN = "token"')
print('updated version-bump')
print('added very verbose mode and fixed chatgpt mess')
