name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
#      id-token: write
      actions: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version using semantic-release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "-vv"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Specify the path if you're not using the default workspace
          path: C:\Users\Pietro\PycharmProjects\semantic-release-test

      - name: Pull latest changes
        run: |
          cd C:\Users\Pietro\PycharmProjects\semantic-release-test
          git pull origin main
